### ISSUE TITLE
uninitialized constant #<Class:0x0000000579eff0>::Line

### ISSUE THREAD

**Issue by CloCkWeRX** [sous-chefs/line#66]
```ruby-2.3.1```
```Starting Chef Client, version 12.8.1```

```
Dans-MacBook-Pro:htw_infra dan$ cat Berksfile.lock  | grep line
  line (= 0.6.3)
  line (0.6.3)
    line (>= 0.0.0)
```

```
================================================================================
Recipe Compile Error in /tmp/chef/cookbooks/line/resources/add_to_list.rb
================================================================================

NameError
---------
uninitialized constant #<Class:0x0000000579eff0>::Line

Cookbook Trace:
---------------
  /tmp/chef/cookbooks/line/resources/add_to_list.rb:96:in `block in class_from_file'
  /tmp/chef/cookbooks/line/resources/add_to_list.rb:92:in `class_eval'
  /tmp/chef/cookbooks/line/resources/add_to_list.rb:92:in `class_from_file'

Relevant File Content:
----------------------
/tmp/chef/cookbooks/line/resources/add_to_list.rb:

 89:    end
 90:  end
 91:  
 92:  action_class.class_eval do
 93:    require 'fileutils'
 94:    require 'tempfile'
 95:  
 96>>   include Line::Helper
 97:  end
 98:  
```

It might just be as simple as ::Line to specify current namespace.

**Comment by CloCkWeRX** [comment]
Let me bump to 1.0.3+ and try again
