### ISSUE TITLE
append_if_no_line broken since v1.1.0

### ISSUE THREAD

**Issue by hgregorian** [sous-chefs/line#84]
Working in v1.0.6

```
       Recipe: test::default
         * append_if_no_line[maybe there, maybe not] action edit[2018-04-19T20:59:11+00:00] INFO: Processing append_if_no_line[maybe there, maybe not] action edit (test::default line 1)
       
           - Updating file /tmp/test_file

```

Not working in v.1.1.0 (same results for recently released v1.1.1)

```
       Recipe: test::default
         * append_if_no_line[maybe there, maybe not] action edit[2018-04-19T20:56:50+00:00] INFO: Processing append_if_no_line[maybe there, maybe not] action edit (test::default line 1)
       
           
           ================================================================================
           Error executing action `edit` on resource 'append_if_no_line[maybe there, maybe not]'
           ================================================================================
           
           RuntimeError
           ------------
           File /tmp/test_file not found
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/line/resources/append_if_no_line.rb:10:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test/recipes/default.rb
           
             1: append_if_no_line "maybe there, maybe not" do
             2:   path '/tmp/test_file'
             3:   line "Hello World!"
             4: end
             5: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test/recipes/default.rb:1:in `from_file'
           
           append_if_no_line("maybe there, maybe not") do
             action [:edit]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :append_if_no_line
             cookbook_name "test"
             recipe_name "default"
             path "/tmp/test_file"
             line "Hello World!"
           end
           
           Platform:
           ---------
           x86_64-linux
           
       [2018-04-19T20:56:50+00:00] INFO: Running queued delayed notifications before re-raising exception
```

**Comment by MarkGibbons** [comment]
Hi @hgregorian,

  Yes, that changed. The change was a deliberate choice.  The line cookbook doesn't really have a lot of information to create the file,  the owner, group, mode bits are all missing.  Using a file statement to create the file before running line is recommended.

Mark

**Comment by hgregorian** [comment]
Understood @MarkGibbons 

My confusion comes from the CHANGELOG entries (or lack thereof):

Suggests that the functionality was added:
```
v1.1.1 (2018-04-16)

Allow appending to an empty file
```

Makes no mention of not creating a file if it does not exist:
```
v1.1.0 (2018-03-26)

Rework delete_lines to use file provider subresource.
Support matching with regexps in addition to strings with delete_lines.
Rework append_if_no_line to use file provider subresource.
Fix edge conditions around files-with-no-trailing-CR being fed to append_if_no_line.
Remove library helpers.
Remove the escape_regexp and escape_string methods in favour of native Regexp.escape
```

Thanks for the clarification though!

**Comment by MarkGibbons** [comment]
1.1.1 was just for existing but empty files, just that edge case. I'm checking on why the raise error for non existent file was added.

**Comment by MarkGibbons** [comment]
The ignore_missing property will be added to most of the resources to get back the old behavior.  There's an ongoing discussion as to making the old behavior of creating the file be the default.  I'm going to close this issue now.  It sounds like you have the information you need and a partial fix will be available soon.

Thanks,
   Mark
