### ISSUE TITLE
Tar Header Octal string (ArgumentError)

### ISSUE THREAD

**Issue by goldenpuon** [sous-chefs/line#88]
Hi,

With version 1.1.1, I receive the following error when running a berks install caused by an invalid tar header.

```[C:\Users\rwise25\Desktop\Hadoop-HPC Projects\Chef\auto-bootstrap\cookbooks\service-config] [10:41:57]
# [master ≡ +110 ~3 -1 !]> cat berksfile
# frozen_string_literal: true
source 'https://supermarket.chef.io'
cookbook 'chef-client'
cookbook 'line', '~> 1.1.1'


metadata
`[C:\Users\REMOVED\Desktop\Hadoop-HPC Projects\Chef\auto-bootstrap\cookbooks\service-config] [10:41:59]
# [master ≡ +110 ~3 -1 !]> berks install
Resolving cookbook dependencies...
Fetching 'service-config' from source at .
Fetching cookbook index from https://supermarket.chef.io...
Using chef-client (10.0.4)
Using logrotate (2.2.0)
Using service-config (0.1.0) from source at .
Using windows (4.2.2)
Using cron (5.1.0)
Installing line (1.1.1)
c:/opscodeNEW/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_header.rb:128:in `strict_oct': "\x80\x00\x0
\x00d\x9E\xD3\xD9" is not an octal string (ArgumentError)
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_header.rb:108:in `from'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_reader.rb:59:in `each'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:27:i
 `block in extract'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_reader.rb:29:in `new'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:118:
n `reader'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:25:i
 `extract'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive.rb:33:in `e
tract'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/community_rest.rb:16:
n `unpack'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/community_rest.rb:102
in `download'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:70:in `
ry_download'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:40:in `
lock in download'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:39:in `
ach'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:39:in `
ownload'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/installer.rb:108:in `
nstall'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/installer.rb:181:in `
lock (2 levels) in install_from_universe'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_
ask_executor.rb:24:in `block in execute'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronizatio
/mri_lockable_object.rb:38:in `block in synchronize'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronizatio
/mri_lockable_object.rb:38:in `synchronize'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronizatio
/mri_lockable_object.rb:38:in `synchronize'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_
ask_executor.rb:19:in `execute'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in
`safe_execute'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:i
 `block in execute'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_
hread_pool_executor.rb:348:in `run_task'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_
hread_pool_executor.rb:337:in `block (3 levels) in create_worker'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_
hread_pool_executor.rb:320:in `loop'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_
hread_pool_executor.rb:320:in `block (2 levels) in create_worker'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_
hread_pool_executor.rb:319:in `catch'
        from c:/opscodeNEW/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_
hread_pool_executor.rb:319:in `block in create_worker```

**Comment by goldenpuon** [comment]
This is a bug with rubygems, NOT the cookbook. Reference: https://github.com/berkshelf/berkshelf/issues/1744
********************
Closing issue.
